[project]
name = "simple-media-jukebox"
version = "7.1.0"
description = "A simple command-line media indexer and jukebox."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mutagen>=1.47.0",
]

[tool.uv]
dev-dependencies = []
